# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Terno de Reis - Grupo Olaria
email: ternodatmc@gmail.com
description: Acervo virtual do Terno de Reis da cidade de Vitória da Conquista - Bahia, organizado pelo grupo Olaria.
baseurl: "/" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  olariagrupo

# Build settings
markdown: kramdown
